"""initial schema

Revision ID: bcb78cf2615a
Revises: 
Create Date: 2016-01-27 02:15:27.539088

"""

# revision identifiers, used by Alembic.
revision = 'bcb78cf2615a'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('compound',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('smiles', sa.String(length=750), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_compound_external_id'), 'compound', ['external_id'], unique=True)
    op.create_table('species',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_species_external_id'), 'species', ['external_id'], unique=True)
    op.create_table('target',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('species_id', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ),
    sa.ForeignKeyConstraint(['species_id'], ['species.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_target_external_id'), 'target', ['external_id'], unique=True)
    op.create_table('activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('relation', sa.Enum('=', '>', '<', '<=', '>=', name='relation'), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('assay_type', sa.Enum('ADMET', 'Binding', 'Functional', 'Property', 'Unassigned', name='assay_type'), nullable=False),
    sa.Column('activity_type', sa.Enum('Kd', 'AC50', 'Potency', 'XC50', 'IC50', 'Ki', 'EC50', name='activity_type'), nullable=False),
    sa.Column('confidence_score', sa.Integer(), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('compound_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['compound_id'], ['compound.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['target.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_activity_confidence_score'), 'activity', ['confidence_score'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activity_confidence_score'), table_name='activity')
    op.drop_table('activity')
    op.drop_index(op.f('ix_target_external_id'), table_name='target')
    op.drop_table('target')
    op.drop_index(op.f('ix_species_external_id'), table_name='species')
    op.drop_table('species')
    op.drop_index(op.f('ix_compound_external_id'), table_name='compound')
    op.drop_table('compound')
    op.drop_table('source')
    ### end Alembic commands ###
